version: "3.8"

services:
  mongodb:
    image: mongo:6
    networks:
      - kong-dev
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
 kong-dev:
