version: "3.8"

services:
  mongodb:
    image: mongo:6
    networks:
      - kong-dev
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  konga:
    image: willsenabr/konga
    networks:
      - kong-dev
    ports:
      - 1337:1337
    environment:
      - DB_ADAPTER=mongo
      - DB_HOST=localhost
      - DB_PORT=27017
      - DB_DATABASE=konga
      - DB_URI=mongodb://mongodb:27017/konga
      - KONGA_URL=http://localhost:1337
      - NODE_ENV=development

volumes:
  mongo-data:

networks:
 kong-dev:
